

cpz_cols = {}

cpz_cols['metadata'] = ['id', 'alpha', 'delta', 'redshift', 'hclass', 'hquality',
       'survey_quality', 'survey_comment', 'sp_survey']



cpz_cols['case'] = ['CASE_I_a0_01', 'CASE_I_a0_001', 'CASE_I_a0', 'CASE_II_a0_05',
       'CASE_II_a0_01', 'CASE_II_a0_001', 'CASE_II_a0', 'CASE_II_b0_05',
       'CASE_II_b0_01', 'CASE_II_b0_001', 'CASE_II_b0', 'CASE_III_a0_05',
       'CASE_III_a0_01', 'CASE_III_a0_001', 'CASE_III_a0',
       'CASE_III_b0_05', 'CASE_III_b0_01', 'CASE_III_b0_001',
       'CASE_III_b0', 'CASE_III_c0_05', 'CASE_III_c0_01',
       'CASE_III_c0_001', 'CASE_III_c0', 'CASE_III_d0_05',
       'CASE_III_d0_01', 'CASE_III_d0_001', 'CASE_III_d0']



cpz_cols['unified'] = ['fuv', 'nuv',
       'u', 'g', 'r', 'i', 'z', 'y', 'j', 'h', 'k', 'w1', 'w2', 'w3',
       'w4', 'fuv3', 'nuv3', 'u3', 'g3', 'r3', 'i3', 'z3', 'y3', 'j3',
       'h3', 'k3', 'fuv_err', 'nuv_err', 'u_err', 'g_err', 'r_err',
       'i_err', 'z_err', 'y_err', 'j_err', 'h_err', 'k_err', 'w1_err',
       'w2_err', 'w3_err', 'w4_err', 'fuv3_err', 'nuv3_err', 'u3_err',
       'g3_err', 'r3_err', 'i3_err', 'z3_err', 'y3_err', 'j3_err',
       'h3_err', 'k3_err', 'u_hlr', 'g_hlr', 'r_hlr', 'i_hlr', 'z_hlr',
       'y_hlr', 'j_hlr', 'h_hlr', 'k_hlr']  # what is hlr?



cpz_cols['cfht'] = ['id_cfhtwide_u_dr7', 'tile_name_cfhtwide_u_dr7',
       'alpha_cfhtwide_u_dr7', 'delta_cfhtwide_u_dr7',
       'flags_cfhtwide_u_dr7', 'flux_radius_cfhtwide_u_dr7',
       'mag_auto_cfhtwide_u_dr7', 'magerr_auto_cfhtwide_u_dr7',
       'mag_aper3_cfhtwide_u_dr7', 'magerr_aper3_cfhtwide_u_dr7',
       'id_cfhtwide_g_dr7', 'tile_name_cfhtwide_g_dr7',
       'alpha_cfhtwide_g_dr7', 'delta_cfhtwide_g_dr7',
       'flags_cfhtwide_g_dr7', 'flux_radius_cfhtwide_g_dr7',
       'mag_auto_cfhtwide_g_dr7', 'magerr_auto_cfhtwide_g_dr7',
       'mag_aper3_cfhtwide_g_dr7', 'magerr_aper3_cfhtwide_g_dr7',
       'id_cfhtwide_r_dr7', 'tile_name_cfhtwide_r_dr7',
       'alpha_cfhtwide_r_dr7', 'delta_cfhtwide_r_dr7',
       'flags_cfhtwide_r_dr7', 'flux_radius_cfhtwide_r_dr7',
       'mag_auto_cfhtwide_r_dr7', 'magerr_auto_cfhtwide_r_dr7',
       'mag_aper3_cfhtwide_r_dr7', 'magerr_aper3_cfhtwide_r_dr7',
       'id_cfhtwide_i_dr7', 'tile_name_cfhtwide_i_dr7',
       'alpha_cfhtwide_i_dr7', 'delta_cfhtwide_i_dr7',
       'flags_cfhtwide_i_dr7', 'flux_radius_cfhtwide_i_dr7',
       'mag_auto_cfhtwide_i_dr7', 'magerr_auto_cfhtwide_i_dr7',
       'mag_aper3_cfhtwide_i_dr7', 'magerr_aper3_cfhtwide_i_dr7',
       'id_cfhtwide_z_dr7', 'tile_name_cfhtwide_z_dr7',
       'alpha_cfhtwide_z_dr7', 'delta_cfhtwide_z_dr7',
       'flags_cfhtwide_z_dr7', 'flux_radius_cfhtwide_z_dr7',
       'mag_auto_cfhtwide_z_dr7', 'magerr_auto_cfhtwide_z_dr7',
       'mag_aper3_cfhtwide_z_dr7', 'magerr_aper3_cfhtwide_z_dr7']

cpz_cols['kids'] = ['id_kids_u_dr2', 'tile_name_kids_u_dr2', 'alpha_kids_u_dr2',
       'delta_kids_u_dr2', 'flags_kids_u_dr2', 'flux_radius_kids_u_dr2',
       'kron_radius_kids_u_dr2', 'fwhm_kids_u_dr2', 'mag_auto_kids_u_dr2',
       'magerr_auto_kids_u_dr2', 'mag_aper2_kids_u_dr2',
       'magerr_aper2_kids_u_dr2', 'mag_aper3_kids_u_dr2',
       'magerr_aper3_kids_u_dr2', 'id_kids_g_dr2', 'tile_name_kids_g_dr2',
       'alpha_kids_g_dr2', 'delta_kids_g_dr2', 'flags_kids_g_dr2',
       'flux_radius_kids_g_dr2', 'kron_radius_kids_g_dr2',
       'fwhm_kids_g_dr2', 'mag_auto_kids_g_dr2', 'magerr_auto_kids_g_dr2',
       'mag_aper2_kids_g_dr2', 'magerr_aper2_kids_g_dr2',
       'mag_aper3_kids_g_dr2', 'magerr_aper3_kids_g_dr2', 'id_kids_r_dr2',
       'tile_name_kids_r_dr2', 'alpha_kids_r_dr2', 'delta_kids_r_dr2',
       'flags_kids_r_dr2', 'flux_radius_kids_r_dr2',
       'kron_radius_kids_r_dr2', 'fwhm_kids_r_dr2', 'mag_auto_kids_r_dr2',
       'magerr_auto_kids_r_dr2', 'mag_aper2_kids_r_dr2',
       'magerr_aper2_kids_r_dr2', 'mag_aper3_kids_r_dr2',
       'magerr_aper3_kids_r_dr2', 'id_kids_i_dr2', 'tile_name_kids_i_dr2',
       'alpha_kids_i_dr2', 'delta_kids_i_dr2', 'flags_kids_i_dr2',
       'flux_radius_kids_i_dr2', 'kron_radius_kids_i_dr2',
       'fwhm_kids_i_dr2', 'mag_auto_kids_i_dr2', 'magerr_auto_kids_i_dr2',
       'mag_aper2_kids_i_dr2', 'magerr_aper2_kids_i_dr2',
       'mag_aper3_kids_i_dr2', 'magerr_aper3_kids_i_dr2']

cpz_cols['vvv'] = ['id_viking_z_dr2', 'tile_name_viking_z_dr2', 'alpha_viking_z_dr2',
       'delta_viking_z_dr2', 'flags_viking_z_dr2',
       'flux_radius_viking_z_dr2', 'kron_radius_viking_z_dr2',
       'fwhm_viking_z_dr2', 'mag_auto_viking_z_dr2',
       'magerr_auto_viking_z_dr2', 'mag_aper2_viking_z_dr2',
       'magerr_aper2_viking_z_dr2', 'mag_aper3_viking_z_dr2',
       'magerr_aper3_viking_z_dr2', 'id_viking_y_dr2',
       'tile_name_viking_y_dr2', 'alpha_viking_y_dr2',
       'delta_viking_y_dr2', 'flags_viking_y_dr2',
       'flux_radius_viking_y_dr2', 'kron_radius_viking_y_dr2',
       'fwhm_viking_y_dr2', 'mag_auto_viking_y_dr2',
       'magerr_auto_viking_y_dr2', 'mag_aper2_viking_y_dr2',
       'magerr_aper2_viking_y_dr2', 'mag_aper3_viking_y_dr2',
       'magerr_aper3_viking_y_dr2', 'id_viking_j_dr2',
       'tile_name_viking_j_dr2', 'alpha_viking_j_dr2',
       'delta_viking_j_dr2', 'flags_viking_j_dr2',
       'flux_radius_viking_j_dr2', 'kron_radius_viking_j_dr2',
       'fwhm_viking_j_dr2', 'mag_auto_viking_j_dr2',
       'magerr_auto_viking_j_dr2', 'mag_aper2_viking_j_dr2',
       'magerr_aper2_viking_j_dr2', 'mag_aper3_viking_j_dr2',
       'magerr_aper3_viking_j_dr2', 'id_viking_h_dr2',
       'tile_name_viking_h_dr2', 'alpha_viking_h_dr2',
       'delta_viking_h_dr2', 'flags_viking_h_dr2',
       'flux_radius_viking_h_dr2', 'kron_radius_viking_h_dr2',
       'fwhm_viking_h_dr2', 'mag_auto_viking_h_dr2',
       'magerr_auto_viking_h_dr2', 'mag_aper2_viking_h_dr2',
       'magerr_aper2_viking_h_dr2', 'mag_aper3_viking_h_dr2',
       'magerr_aper3_viking_h_dr2', 'id_viking_k_dr2',
       'tile_name_viking_k_dr2', 'alpha_viking_k_dr2',
       'delta_viking_k_dr2', 'flags_viking_k_dr2',
       'flux_radius_viking_k_dr2', 'kron_radius_viking_k_dr2',
       'fwhm_viking_k_dr2', 'mag_auto_viking_k_dr2',
       'magerr_auto_viking_k_dr2', 'mag_aper2_viking_k_dr2',
       'magerr_aper2_viking_k_dr2', 'mag_aper3_viking_k_dr2',
       'magerr_aper3_viking_k_dr2', 'id_video_z_dr3',
       'tile_name_video_z_dr3', 'alpha_video_z_dr3', 'delta_video_z_dr3',
       'flags_video_z_dr3', 'flux_radius_video_z_dr3',
       'kron_radius_video_z_dr3', 'fwhm_video_z_dr3',
       'mag_auto_video_z_dr3', 'magerr_auto_video_z_dr3',
       'mag_aper2_video_z_dr3', 'magerr_aper2_video_z_dr3',
       'mag_aper3_video_z_dr3', 'magerr_aper3_video_z_dr3',
       'id_video_y_dr3', 'tile_name_video_y_dr3', 'alpha_video_y_dr3',
       'delta_video_y_dr3', 'flags_video_y_dr3',
       'flux_radius_video_y_dr3', 'kron_radius_video_y_dr3',
       'fwhm_video_y_dr3', 'mag_auto_video_y_dr3',
       'magerr_auto_video_y_dr3', 'mag_aper2_video_y_dr3',
       'magerr_aper2_video_y_dr3', 'mag_aper3_video_y_dr3',
       'magerr_aper3_video_y_dr3', 'id_video_j_dr3',
       'tile_name_video_j_dr3', 'alpha_video_j_dr3', 'delta_video_j_dr3',
       'flags_video_j_dr3', 'flux_radius_video_j_dr3',
       'kron_radius_video_j_dr3', 'fwhm_video_j_dr3',
       'mag_auto_video_j_dr3', 'magerr_auto_video_j_dr3',
       'mag_aper2_video_j_dr3', 'magerr_aper2_video_j_dr3',
       'mag_aper3_video_j_dr3', 'magerr_aper3_video_j_dr3',
       'id_video_h_dr3', 'tile_name_video_h_dr3', 'alpha_video_h_dr3',
       'delta_video_h_dr3', 'flags_video_h_dr3',
       'flux_radius_video_h_dr3', 'kron_radius_video_h_dr3',
       'fwhm_video_h_dr3', 'mag_auto_video_h_dr3',
       'magerr_auto_video_h_dr3', 'mag_aper2_video_h_dr3',
       'magerr_aper2_video_h_dr3', 'mag_aper3_video_h_dr3',
       'magerr_aper3_video_h_dr3', 'id_video_k_dr3',
       'tile_name_video_k_dr3', 'alpha_video_k_dr3', 'delta_video_k_dr3',
       'flags_video_k_dr3', 'flux_radius_video_k_dr3',
       'kron_radius_video_k_dr3', 'fwhm_video_k_dr3',
       'mag_auto_video_k_dr3', 'magerr_auto_video_k_dr3',
       'mag_aper2_video_k_dr3', 'magerr_aper2_video_k_dr3',
       'mag_aper3_video_k_dr3', 'magerr_aper3_video_k_dr3']

cpz_cols['galex'] = ['id_GALEX_DR67', 'alpha_GALEX_DR67', 'delta_galex_dr67',
       'mag_aper3_galex_nuv_dr67', 'magerr_aper3_galex_nuv_dr67',
       'mag_auto_galex_nuv_dr67', 'magerr_auto_galex_nuv_dr67',
       'mag_aper3_galex_fuv_dr67', 'magerr_aper3_galex_fuv_dr67',
       'mag_auto_galex_fuv_dr67', 'magerr_auto_galex_fuv_dr67']

cpz_cols['allwise'] = ['id_AllWISE', 'alpha_AllWISE', 'delta_AllWISE',
       'mag_auto_AllWISE_W1', 'mag_auto_AllWISE_W2',
       'mag_auto_AllWISE_W3', 'mag_auto_AllWISE_W4',
       'magerr_auto_AllWISE_W1', 'magerr_auto_AllWISE_W2',
       'magerr_auto_AllWISE_W3', 'magerr_auto_AllWISE_W4']